### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JayFoxRox** [JeremyAnsel/xwa_TgSmush#1]
What license does this have?

I'd like to use it in a "GPLv2 or later" project.

So license as "GPLv2 or later", "BSD", "CC0" or similar would be appreciated.

**Comment by JeremyAnsel** [comment]
Hello,
This is licensed under the MIT license (See `LICENSE.txt`).

**Comment by JayFoxRox** [comment]
Awesome! Thanks.

(Closed in https://github.com/JeremyAnsel/xwa_TgSmush/commit/a7432195e4b0ba484f918b1eb457b910b537a1e5 by introducing the MIT `LICENSE.txt`)
